name: github_parser

services:
  github-scraper-api:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    image: github-api-dev
    container_name: api_dev
    env_file:
      - ./.env/local/postgres
      - ./.env/local/app
    networks:
      - dev-network
    entrypoint:
      - /usr/bin/env bash "/workspaces/api/.devcontainer/postCreateCommand.sh"
    develop:
      # Create a `watch` configuration to update the app
      #
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml

  postgres:
    image: postgres:15
    container_name: postgres-dev
    # TODO: add env from .env
    env_file:
      - ./.env/local/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - dev-network

volumes:
  postgres_data:

networks:
  dev-network:
