site_name: github-scraper
repo_url: https://github.com/sbkubric/github-scraper
site_url: https://sbkubric.github.io/github-scraper
site_description: An attempt to build microservice-based scraper with backend powered by FastAPI
site_author: Stan aka SBKubric Bogatskiy
edit_uri: edit/main/docs/
repo_name: sbkubric/github-scraper
copyright: Maintained by <a href="https://sbkubric.com">sbkubric</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [github_scraper]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sbkubric/github-scraper
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/github-scraper

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
